### ISSUE TITLE
Addition of new run on the client side

### ISSUE THREAD

**Issue by meir412** [meir412/running_website#3]
## Description
* Currently, new runs can only be added to the db on the server side via fixtures or by using the admin portal.
* There is a view and a template for adding a new run on the client side called `addNewRun`, but they currently only hold a partial form which doesn't have any effect upon submission.
* In this issue, we'll develop the logic and ui needed so that the user could add a new run by filling out `start_time`, `time_sec` and `route`.
* `route` is the trickiest data point to receive from the user. At the first stage, `route` will be added via a gpx file uploaded by the user (check if this is supported on heroku). The required `LineStringField` value will be extracted from the gpx file on the back-end, and will also require a few validations.
* The run's `runner` value will be extracted from the logged in user's details using the django authentication framework.

## Tasks

- [ ] Edit existing view

- [ ] Edit existing template

- [ ] Edit existing form (if neccesary this might be a template)

- [ ] Add logic for parsing gpx files and extracting the `LineStringField` value
